# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 286629992628e495a2c471c397d204b3f03862ee78a4e9f73ad75c6a41c9a54afaf7e933f3bd91e090761a2f5910b9d2cdc5aa6553e6bcc9b39f5b4364416371

test:
  secret_key_base: 360e4a45cb62198c272fa6c4b8bad2c4307bf87ef48bda1452ac1bfabb4dc1265d5c551ddd0363cbeeb6037aef603dbbe8cb131c2a88ea3b5d06b2046df2fe51

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
